[project]
name = "bookclub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "PyQt6>=6.6.0",
    "bs4>=0.0.2",
    "chromadb>=0.4.0",
    "ollama>=0.1.0",
]
